### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by kylewhirl** [bradsjm/hassio-addons#19]
Would it possible to run Hyperion with root access? Then hardware lights would be controllable

**Comment by bradsjm** [comment]
Hyperion-NG is explicitly NOT supported in a container by the authors. The reason for that is most likely because containers don't play nicely with hardware. If you are trying to control any attached lighting you should use a dedicated Pi or similar device to run Hyperion on. 

FYI - The add-on already asks for every possible hardware privilege available from Home Assistant:

```
  "privileged": [
    "SYS_ADMIN",
    "SYS_RAWIO"
  ],
  "uart": true,
  "usb": true,
  "video": true,
  "gpio": true,
  "devices": [
    "/dev/spidev0.0",
    "/dev/vchiq",
    "/dev/amvideo",
    "/dev/fb0",
    "/dev/mem"
  ],
 ```
Side note - The point of a docker container (hence the name container) is that everything in a container is contained, so it has no rights outside of the container to anything such as hardware or even other containers or even the computer the container is running on without the host system allowing it (in this case Hassio).
