### ISSUE TITLE
* failed to open vchiq instance

### ISSUE THREAD

**Issue by HITMIK** [bradsjm/hassio-addons#8]
This problem with only HomeAssistant addons. With I start hyperion-ng in debian its OK.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
* failed to open vchiq instance
[cmd] /run.sh exited 255
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by boyfromgermany** [comment]
same issue for me 
It worked after the first install , but after a restart it gave this error
even after restarting the host and reinstalling the addon it wont even start once anymore
even with  sudo chmod 777 /dev/vchiq it refuses to start

**Comment by bradsjm** [comment]
Re-installing the add on will not remove the configuration file which is stored under the config folder where the other Home Assistant configuration files are which is why I suspect it won't start even when re-installing.

I've added /dev/vchiq to the list of mapped devices in the add-on configuration, refresh the repository before re-installing to see if that resolves the error.

**Comment by HITMIK** [comment]
@bradsjm THX, this is fix for me :-)
